"""create animales table with audit columns

Revision ID: 80c53f321b60
Revises: 3635a4326110
Create Date: 2026-03-18 02:30:02.063561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '80c53f321b60'
down_revision: Union[str, None] = '3635a4326110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animales',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('especie', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario_creacion', sa.Integer(), nullable=False),
    sa.Column('id_usuario_edita', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_edicion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario_creacion'], ['usuarios.id_usuario'], name='fk_base_usuario_creacion'),
    sa.ForeignKeyConstraint(['id_usuario_edita'], ['usuarios.id_usuario'], name='fk_base_usuario_edita'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animales_id'), 'animales', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_animales_id'), table_name='animales')
    op.drop_table('animales')
    # ### end Alembic commands ###
