"""create citas table with audit columns and relations

Revision ID: 97cbda930bf2
Revises: b35f08669de0
Create Date: 2026-03-18 02:48:13.290190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '97cbda930bf2'
down_revision: Union[str, None] = 'b35f08669de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citas',
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('id_animal', sa.Integer(), nullable=False),
    sa.Column('id_veterinario', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario_creacion', sa.Integer(), nullable=False),
    sa.Column('id_usuario_edita', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_edicion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_animal'], ['animales.id'], name='fk_cita_animal'),
    sa.ForeignKeyConstraint(['id_usuario_creacion'], ['usuarios.id_usuario'], name='fk_base_usuario_creacion'),
    sa.ForeignKeyConstraint(['id_usuario_edita'], ['usuarios.id_usuario'], name='fk_base_usuario_edita'),
    sa.ForeignKeyConstraint(['id_veterinario'], ['usuarios.id_usuario'], name='fk_cita_veterinario'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citas_id'), 'citas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_citas_id'), table_name='citas')
    op.drop_table('citas')
    # ### end Alembic commands ###
