"""add gatos and perros tables with inheritance

Revision ID: b35f08669de0
Revises: 80c53f321b60
Create Date: 2026-03-18 02:36:31.306232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b35f08669de0'
down_revision: Union[str, None] = '80c53f321b60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['animales.id'], name='fk_gato_animal'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['animales.id'], name='fk_perro_animal'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('animales', sa.Column('tipo', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animales', 'tipo')
    op.drop_table('perros')
    op.drop_table('gatos')
    # ### end Alembic commands ###
