"""create consultas table with audit columns and relations

Revision ID: e1bb86702a2b
Revises: 97cbda930bf2
Create Date: 2026-03-18 03:05:20.573645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e1bb86702a2b'
down_revision: Union[str, None] = '97cbda930bf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultas',
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('diagnostico', sa.String(length=500), nullable=False),
    sa.Column('tratamiento', sa.String(length=500), nullable=False),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('tipo_consulta', sa.String(length=20), nullable=False),
    sa.Column('motivo_revision', sa.String(length=200), nullable=True),
    sa.Column('proxima_cita', sa.Date(), nullable=True),
    sa.Column('nivel_urgencia', sa.Integer(), nullable=True),
    sa.Column('sintomas', sa.String(length=500), nullable=True),
    sa.Column('id_cita', sa.Integer(), nullable=False),
    sa.Column('id_animal', sa.Integer(), nullable=False),
    sa.Column('id_veterinario', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario_creacion', sa.Integer(), nullable=False),
    sa.Column('id_usuario_edita', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_edicion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_animal'], ['animales.id'], name='fk_consulta_animal'),
    sa.ForeignKeyConstraint(['id_cita'], ['citas.id'], name='fk_consulta_cita'),
    sa.ForeignKeyConstraint(['id_usuario_creacion'], ['usuarios.id_usuario'], name='fk_base_usuario_creacion'),
    sa.ForeignKeyConstraint(['id_usuario_edita'], ['usuarios.id_usuario'], name='fk_base_usuario_edita'),
    sa.ForeignKeyConstraint(['id_veterinario'], ['usuarios.id_usuario'], name='fk_consulta_veterinario'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultas_id'), 'consultas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consultas_id'), table_name='consultas')
    op.drop_table('consultas')
    # ### end Alembic commands ###
